
ls -al .

if (which df) {
    echo "df is installed on the system..."  
    echo 'and I\'m echoing with single quotes'
} else {
    echo "Df is not available"
}

function someFunction {
    echo "someFunction was called"
    if(3 = 5){
        echo "3 == 5, what?!!!!"
    }
}

command myCommand {
    echo "In a pretty awesome command";
}

'''
I'm writing a long line of text....
Actually I lied I'm writing a multi line stirng
which wraps and includes line breaks...
'''

"""
I'm doing the smae thing with the " symbol this time.
It has some lines"
"""

$describes = [];

function describe {
    
    $describes.push {
         name: $1,
         'block': $2
     }

}

@someFunction "Argument" 1 null function {
    echo "Block";
}

@describe "writing a spec in universal shell" function {

    @it "should be able to have nested functions" function {
        echo "In a nested function"
    }    
}
