
ls -al .

if (which df) {
    echo "df is installed on the system..."  
    echo 'and I\'m echoing with single quotes'
} else {
    echo "Df is not available"
}

function someFunction {
    echo "someFunction was called"
    if(3 = 5){
        echo "3 == 5, what?!!!!"
    }
}

command myCommand {
    echo "In a pretty awesome command";
}

'''
I'm writing a long line of text....
Actually I lied I'm writing a multi line stirng
which wraps and includes line breaks...
'''

"""
I'm doing the smae thing with the " symbol this time.
It has some lines"
"""

@someFunction "Argument" 1 null {
    echo "Block";
}

@describe "writing a spec in universal shell" {
    
    @it "should be able to have nexted anonymous blocks" {
        echo "And we're in a nested block..."
    }
}
